language: haxe
dist: xenial

haxe:
  - 3.4.7
  - development

install:
  haxelib dev hxnodejs .

script:
  - haxe build.hxml
  - haxelib git dox https://github.com/HaxeFoundation/dox
  - haxe doc.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: development
    condition: $TRAVIS_EVENT_TYPE != "cron"
  skip_cleanup: true
